# Perform 'apt update'
- name: Run 'apt update' proactively to avoid the need for future 'apt' invocations to do it
  apt:
    force_apt_get: yes
    update_cache: yes

# Disable root login via password
- name: Disable root login via password
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
  notify: restart ssh

# Disable root login via SSH
- name: Disable root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart ssh

# Disable password authentication via SSH
- name: Disable password authentication via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart ssh

# Enable SSH key-based authentication
- name: Enable SSH key-based authentication
  authorized_key:
    user: ubuntu
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present

# Set up unattended upgrades
- name: Set up unattended upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configure unattended-upgrades
  template:
    src: ~/DevOps/GL/gl-final/roles/hardening/templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  notify: restart unattended-upgrades